name: Deploy to GitHub Pages

# currently not paused
on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8 # Or npm/yarn if you're using them

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: pnpm install
      - run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
